concord-consortium/connected-bio-spaces

.travis.yml
s3_deploy.sh
s3_website.yml

Super quick changes to deploy to S3 and update the version of `node` to LTS to avoid the binary-building issues we saw in CLUE.
https://travis-ci.com/concord-consortium/connected-bio-spaces
http://connected-bio-spaces.concord.org/branch/travis-deploy/

Travis deploy

---

src/components/charts/line-graph.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.test.ts
src/models/spaces/charts/chart-data.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

This is a small PR to ensure we always retain all data from a data set, and improves handling of scaling on charts with some additional optional parameters to datasets:
fixedMin: can set to 0 to always start Y at 0
fixedMax: can set to a known quantity (i.e. 100) to set a constant scale
expandOnly: not compatible with fixedMax, which would override this value, this will ensure that scrolling horizontal line charts don't constantly rescale the upper bounds of the y axis

Chart improvements

---

src/components/charts/bar-chart.tsx
src/components/charts/chart-test.tsx
src/components/charts/line-graph.tsx
src/models/spaces/cell-zoom/cell-zoom.ts
src/models/spaces/charts/chart-data-set.ts
src/utilities/color-utils.ts

Bar charts changed to  display each data series as a different color, plus moved color helper functions to separate utility file and adjusted line rendering to use new helpers. I'm not sure at this time whether we should retain the ability to show datasets as one color on a bar chart - I haven't seen a design requirement for this as yet so I've left it out for now.

Bar chart colors

---

src/components/spaces/cell-zoom-space.tsx
src/components/spaces/cell-zoom/OrganelleWrapper.tsx
src/components/spaces/cell-zoom/cell-mouse.ts
src/models/spaces/cell-zoom/cell-zoom-row.ts
src/models/spaces/cell-zoom/cell-zoom.ts
src/models/stores.ts

Per our discussion today, I'm starting on click-to-add mice to the cell view, starting with the ability to show multiple mice at a time. Let me know what you think of the updated state, which looks something like this:
The `CellZoom` model now contains a map of "cell mice" and an array of `CellZoomRow`s. Each row references a mouse from the map of mice - this way we can synchronize updates across views more easily. Most of the state that was previously tracked in the `CellZoom` model (e.g. hovered organelle, active assays) are now stored per-row instead.
I also quickly added cell color so you can see that the cell views are rendering different organisms.

Multiple Cell Views

---

src/components/instructions.sass
src/components/instructions.tsx
src/components/spaces/organisms-space.tsx
src/components/spaces/populations-space.tsx
src/components/two-up-display.tsx
src/models/spaces/organisms/organisms-space.ts
src/models/stores.ts
src/models/ui.ts

Add the organism level markdown instructions via the authoring tool.  Instructions are placed in both right panels of the 4-up display in the organism view.  By default, the top set of instructions is shown (the bottom panel displays the graph/data by default).

162054341 organism authored instructions

---

src/components/charts/bar-chart.tsx
src/components/charts/chart.sass
src/components/charts/chart.tsx
src/components/charts/line-chart-controls.sass
src/components/charts/line-chart.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.ts
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts

This branch includes changes to allow for multiple organism level assays to be displayed in a graph in the right panel which follows the layout/format of the previous version of connected bio.  Graphs are scaled to fit into a given view (which includes changes to allow the population graph to do so as well).  A few notes:
- there is probably some cleanup needed here, but I would rather have people start looking at it sooner rather than later
- Editing my previous comment.  I squashed the commit history down to just two items: the changes to add multiple assays to the graph and the changes to improve graph sizing and scaling.  This cleans up some of the wildness from yesterday.  These commits are not as nuanced as I would like, but it's better than the 10 or so previous commits that had …

162487966 multiple assays

---

src/components/collect-button.tsx
src/models/backpack-mouse.test.ts
src/models/backpack-mouse.ts
src/models/backpack.test.ts
src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts
src/models/spaces/populations/mouse-model/mice.ts

This change has no visible effect, as the allele names are not visible anywhere to the user. However, this makes it so it will be easy to use the correct allele names when we start showing them to the user.

Rename B-b alleles to R-C everywhere

---

src/components/authoring.tsx
src/components/spaces/populations/populations-container.sass
src/components/spaces/populations/populations-container.tsx
src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts
src/models/spaces/populations/mouse-model/mice.ts

This changes the mouse names in a hacky way to deal with the populations info tool, which will not be used soon, and changes the environment button text.

162621888 update mouse names

---

src/components/spaces/populations/populations-container.tsx
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

This reverts the changes in 8eab4b2e61, making it so that getting the
interactive from the mouse-populations model returns the existing
interactive if it is there (like before), but now adding an explicit
`close` method when the component is unmounted to destroy the existing
populations interactive.
[#162707041]

Fix double-populations bug

---

src/components/authoring.tsx
src/components/spaces/organisms/manipulation-controls.tsx
src/components/spaces/organisms/organelle-wrapper.sass
src/components/spaces/organisms/organelle-wrapper.tsx
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.test.ts
src/models/spaces/organisms/organisms-space.ts
src/models/stores.ts

This adds simple props for using or not using the mystery labels for organelles and substances. All view requests for the strings now go through a method in the organismsSpace model.
Adds a quick test, which would be uninteresting except that it exposes an odd MST behavior that we can't create more than one `OrganismsSpaceModel`, as we do in a test's `beforeEach` method, without MobX complaining that we are trying to create two of the same object, specifically not the `OrganismsSpaceModel` but the first `OrganismsRowModel` of each.
That is, the following code
const model1 = OrganismsSpaceModel.create({});
const model2 = OrganismsSpaceModel.create({});   // even with some other properties
throws
[mobx-state-tree] Cannot add an object to a state tree if it is already part of the
same …

Add mystery labels

---

src/components/two-up-display.sass
src/components/two-up-display.tsx
src/components/vars.sass
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

Add styling to the show all/show recent graph data button.  This required some refactoring as this button needed to be shown in the upper-right corner, not in the toolbar.  I still like the idea of having an array of `rightPanelButtons` that we build on a per space basis.  However, some extra tweaking was required to specify how to place a button like the show all/show recent button that gets placed somewhere outside of the toolbar.  For now, I was thinking of these as floating buttons - buttons that float somewhere in the panel which would be determined by a CSS class tied to each button.  Obviously lots of ways of doing this, and I'm not eager to make an unusual case to handle a single button, but I was assuming something like this will probably come up again.

162622045 graph button styling

---

src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts

Previously we were seeing occasional "wrong" mice populations, e.g. all brown mice with hawks in white environment.
This seemed to be being caused by:
1. Limited vertical movement (this has since been fixed)
2. Bugs in code that was supposed to reduce "wrong" color's mating chance.
The mating chance code has been fixed, but it seemed too powerful to run all the time. Now it just runs if the user eliminates one population and then switches environments.
With the fixed vertical movement, we generally don't get wrong results, but this also adds a bit of insurance to make sure we never eliminate the wrong population.
[#163911808]

Insure we never get wrong mouse color population, reduce population when in wrong environment

---

src/components/charts/line-chart.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.ts
src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts
src/models/spaces/populations/mouse-model/mice.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

This adds labels to the chart axes, following the pattern in Dat Cross Dam, and also scales the x axes so that we are showing weeks, where each step is 10 weeks.
This required a small addition to the dataSet model to add an initial max A1 value.

Add graph axes labels and scale for weeks

---

src/components/charts/line-chart-controls.tsx
src/components/charts/line-chart.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.test.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/utilities/data.ts

This downsamples the datapoints displayed by the chart using a downsampling algorithm, [largest triangle one bucket](https://blog.scottlogic.com/2015/11/16/sampling-large-data-in-d3fc.html),	which attempts to preserve major features of the data.
This downsamples the entire dataset every 40 datapoints, and then streams the next 40 points as-is. This avoids downsampling every tick, which causes the data to change every tick, which is visually jarring.
Because the sampled dataset doesn't change over the 40 point window, we could cache it as a further optimization, but the actual sampling is very fast, and so this doesn't seem worth the complications.
This also adds an additional rendering optimization of removing the line tension (smoothing) when we have too many datapoints.

Optimize graph when all data is displayed

---

package-lock.json
package.json
src/components/charts/line-chart.tsx
src/components/spaces/populations/populations-container.tsx
src/models/spaces/charts/chart-annotation.test.ts
src/models/spaces/charts/chart-annotation.ts
src/models/spaces/charts/chart-data.ts
src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

This adds a chart annotation plugin, and adds annotations for the population model.
This adds an annotation model object that tries to simplify the options for how the annotations will look, while still providing a fair bit of customization.
Box annotations were added to the model, and are tested, but in the end were not used for the populations model. The box annotations can be seen at this branch: https://connected-bio-spaces.concord.org/branch/add-chart-annotations/ (Try running the model and switching environments).

Add chart annotations

---

src/components/collect-button.tsx
src/components/spaces/organisms-space.tsx
src/models/spaces/organisms/organisms-space.ts
src/models/stores.ts

This updates the UX from requiring the user to click twice (once on the backpack and once in the row) to single click on the backpack, which auto-populates the first available row, if any.
This also deselects mice on space changes, and on row clearing, to prevent the user from needing to click to deselect a mouse before they can add it.
There is currently no purpose now to a backpack mouse being in a selected state. We can discuss at the meeting whether we should remove this behavior entirely, or if it will come up in a later interaction.

Click to add mice to the organism panel

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

We were not updating the state when the user reset the pop sim and the "add hawks" button would display as "remove hawks" to the user.
[#164438603]

Udate Remove Hawks button state when user resets simulation

---

src/components/authoring.tsx
src/index.tsx
src/utilities/url-params.ts

This is a fairly simple change which takes the authored data from the url, plus the authoring defaults, and passes them to the authoring form to be used as the initial form state.
It also now allows `?authoring` to be in a url with the other parameters, instead of requiring it to be the only url param, to allow it to be added to existing authoring urls. This allows us to take the authored url
http://localhost:8080/?%7B"curriculum"%3A"mouse"....
and get the authoring page version simply by inserting "authoring" after
the ?
http://localhost:8080/?authoring%7B"curriculum"%3A"mouse"
This is a little weird, because unescaped it looks like `?authoring{"curriculum": "mouse", ...}` but it seemed the best way both to be backwards-compatible with just using `?authoring` by itself, and also making …

Load authoring data into form

---

src/components/charts/line-chart.tsx

The population graph was resizing (wiggling) as it switched between x axis labels with different string lengths.  This was caused by some axis label values being integers and others having decimals (such as 180 and 180.5).  Changes round all axis label values on the line graph to eliminate the graph resizing and wiggle effect.

Use integer values on Pop Graph to avoid graph resizing

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

The chart type was not an observable value, so updating it didn't cause a re-render.
I read this to figure out how to fix it: https://github.com/mobxjs/mobx-state-tree#volatile-state

Fix populations graph button selection states

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

Following up on @kswenson's suggestion to remove MobX-specific features from `chartType` functionality. I agree that this is cleaner than setting up observers in volatile state.
http://connected-bio-spaces.concord.org/branch/mst-only-charts/

Removes MobX-specific features from chart type setting

---

src/components/spaces/breeding/breeding-container.tsx

Adjust container class to prevent erroneous cursor from appearing in left panel when breeding.  Disable the inspect and collect button when in left panel and actively breeding (we can turn these back on later when we get to them).

Update cursor and button state

---

src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/models/spaces/breeding/breeding.ts

Add ability for author to turn on or off the breeding level graph types and the breeding level inspect gametes button.  Note that, at present, enabling/disabling inspect gametes has no effect as this button is always disabled (this feature will be used once we implement inspecting gametes).

Add authoring of graph and gametes buttons

---

src/components/spaces/breeding/breeding-container.sass
src/components/spaces/populations/populations-container.sass

Fix indentation in Sass files for proper CSS class parenting.  Make sure population and breeding toolbars are children of each space so proper text colors are shown in toolbar.  
Note: even though the diff if nasty, nothing has changed other than indenting a single block of CSS in two files (github doesn't show this well - and there is a one line fix to a CSS typo).  Anyway, despite the diff appearance, this is a small change.

Fix indentation for proper CSS class parenting

---

src/components/authoring.tsx
src/components/spaces/breeding/breeding-container.tsx

This was bypassed previously because at the time the show/hide gametes button was always disabled.  These changes allow the authoring settings to take effect.

Turn off show gametes when user disables button via authoring tools

---

src/components/spaces/breeding/breeding-container.sass

This PR makes a minor adjustment to the CSS class hierarchy to fix an error introduced in a previous commit.  In making the breeding button classes children of the breeding toolbar, styling was broken on the breed and reset buttons (which are not children of the toolbar).  This PR rolls this change back (it wasn't needed in the previous PR, but was done for consistency with the population level change).  And, again, even though the diff looks big, this is just a tab change.

Fix breed level button styling

---

src/components/colors.scss
src/components/spaces/breeding/arrow-panel.sass
src/components/spaces/breeding/arrow-panel.tsx
src/components/spaces/breeding/breeding-view.sass
src/components/spaces/breeding/breeding-view.tsx
src/components/stacked-organism.sass
src/components/stacked-organism.tsx

Add gamete hover effects into the breeding view when show gametes option is turned on.  Notes:
- a new `ArrowPanel` component takes in an array of `ArrowInfo` objects which specify each hover arrow and then renders the full set of arrows
- additional highlight properties have been added to the React state in the `BreedingView`component to help manage what object a user is hovering over and the subsequent effects that this has on other parts of the UI 
- additional props were added to the `StackedOrganism` to support the new mouse hover effects

Add gamete hover effects in breeding view

---

src/components/spaces/populations/populations-container.sass

One more fix that backtracks an earlier change and unparents a couple of CSS classes from the population level toolbar.  The effect in this case was that we lost the inspect and collect cursors at the population level.

Fix incorrect parenting of CSS classes

---

src/components/app.sass

Having a flex box with centered content was resulting in only a portion of the page content from being accessible within a container with scrollbar.  This quick fix replaces the `align-items: center` so all of the content appears in the scroll container.

Fix authoring page scrolling

---

src/components/spaces/breeding/breeding-view.tsx

Prevent inspection of mice that are not in the active litter (this same rule applies to gamete inspection and collection and needed to be implemented for inspection as well).

prevent inspection of inactive litter mice

---

src/components/spaces/breeding/breeding-container.tsx
src/components/spaces/breeding/breeding-view.tsx
src/components/spaces/breeding/nest-pair.tsx
src/models/backpack-mouse.ts
src/models/backpack.ts
src/models/spaces/breeding/breeding.ts

Add breed level collection of parent/offspring mice in both the nest and breeding views.  When collected, the mouse is cloned as a newly created backpack mouse and added to the backpack.  A reference to the original collected mouse is stored in the backpack store to allow highlighting the mice at the breed level.  The previous implementation of the nest view collection has been removed and replaced with this new model (so we no longer store a reference to the backpack mouse with the NestPair).

Add breed level collection of parent and offspring mice

---

src/components/spaces/organisms/nucleus-view.tsx
src/components/spaces/organisms/organisms-container.tsx
src/models/spaces/organisms/organisms-row.ts

This fixes several issues seen in the nucleus:
1. Zooming to the nucleus, and then either saving state and reloading the page, or going to another space and coming back, will result in seeing the mouse image covering up the nucleus
2. Condensing and/or pairing the chromatin, then leaving the space and coming back will result in animations when you return
3. If you move your cursor in and out of the frame during animation, animation will stutter
3. Console errors after leaving and returning to the nucleus, and then doing anything to the chromatin
The fix can be seen at http://connected-bio-spaces.concord.org/branch/fix-nucleus-initialization/
If you want to test saving state without LARA, use http://connected-bio-spaces.concord.org/branch/fix-nucleus-initialization/?saveToLocalStore

Fix nucleus initialization

---

src/models/spaces/breeding/breeding.ts

This fixes a bug that was seen during the all-hands demo.  If the user is inspecting a litter mouse and the reset litter button is pressed, we hit an exception (as we were trying to inspect a mouse that no longer exists).  This PR clears the inspection info if we are inspecting a litter mouse and the clear litter button is pressed.

Clear inspection when reset litter while inspecting mouse in litter

---

src/components/spaces/breeding/breeding-view.tsx

The PR fixes the following bug discovered in QA: user could click on inactive mice in the litter view and collect/inspect them.  Clicks on inactive mice in the litter view are now ignored.

Fix click on inactive litter mouse

---

src/models/spaces/breeding/breeding.ts

Restore the data panel on the breeding level if we open the user save state and they have begun breeding.  I went with checking if one of the nest pairs had been visited via the `hasBeenVisited` property (rather than checking if a litter array contains mice) since checking `hasBeenVisited` will also handle the following cases:
-user has bred mice and hit the reset button
-user has selected one or more pairs that they want to mark for breeding but hasn't hit breed button yet
Both felt like valid reasons to restore the data panel.  However, I'm open to changing this if we put it in front of users and it is confusing.

Restore data panel if user began breeding

---

src/models/spaces/breeding/breeding.ts
src/models/spaces/organisms/organisms-space.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

Adds new annotations on mutation and inheritance switching, and makes the graph panel the default for every space if no instructions are shown.
A tiny bit of smarts is added to make the graph annotations fit next to each other if they are toggled in short succession. It could definitely be smarter-still (you'll still get overlaps if things are too close too often), but, OTOH, if students are toggling things all the time in short succession, they're using it wrong...

Graph updates

---

src/components/spaces/organisms-space.tsx
src/components/spaces/organisms/organism-view.tsx
src/components/spaces/organisms/organisms-container.tsx
src/components/zoom-control.tsx
src/models/spaces/organisms/organisms-space.ts

This
1. Prevents users from zooming into two rows at the same time (https://www.pivotaltracker.com/story/show/169733198)
2. Handles the case where the user clicks to a different tab and back again (or otherwise changes the visibility of the window), which previously froze the animation, by having it always jump to loading the cell model when the user returns
3. Properly clear organism image when user removes it from the row at the organism level
3. Improve handling of right panel when user removes org from row

Fix zoom issues

---

src/components/charts/line-chart.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.test.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

This PR adds the following improvements to the line chart in the population view:
- filter duplicate x values so that tooltip popup at t = 0 doesn't show additional, unexpected values (with present design, x represents time so we should not have multiple samples at a given x or time value).
- fix tooltip popup colors so that colors match the graph lines and legend
- prevent duplicate values in x axis labels by doing the following: set min axis value to 12 when in "show all data" mode and change rounding of min value to avoid min val and first tick having same value
- round values shown in tooltip popup to use max of 2 decimal places

172274981 graph popups

---

package-lock.json
package.json
src/components/spaces/organisms/cell-models/receptor.json
src/components/spaces/organisms/organelle-wrapper.tsx

This addresses an issue where on slow machines, the model can start before the view starts, and consequently before we're ready to listen to messages from the cell model.
The "stuck signal protein" bug is caused by a signal protein binding, sending the message that it has bound, which is supposed to cause the model to trigger the breaking script, but this doesn't happen because the listener has not been set up.
While it would be good to fix the underlying issue of sending messages before listeners are in place, this simply fixes it by delaying adding the signal proteins until the listeners are ready.

Fix signal binding

---

src/components/spaces/organisms/organelles/g-protein-body.yml

Also rotate the protein body since it's now hanging around more noticeably.
For some reason, this requires some verbose switching of states, which I haven't been able to work out.
[#172377106]

Delay moving protein body for a half second

---

src/components/charts/line-chart.tsx

This PR adds a small fix to put population graph legend items on the same line by making the legend box smaller.  This provides a more consistent, readable layout of legend items (no more two line items) and as a result causes graph overlays to appear in the correct location on ALL graph tabs.

Update population graph legend layout which fixes graph overlay positions

---

src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/components/inspect-panel.sass
src/components/inspect-panel.tsx
src/components/spaces/breeding-space.tsx
src/components/spaces/breeding/nest-pair.sass
src/components/spaces/populations-space.tsx
src/components/spaces/populations/populations-container.tsx
src/components/stacked-organism.sass
src/components/stacked-organism.tsx
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

This PR adds the population level mouse inspect, the ability to author the visibility of the population inspect genotype label, and some small UI fixes.  Changes include:
- inspecting a mouse in the population level now shows the mouse information in the right panel.  Because of overlap, the breeding and population inspect have been collapsed into a single React component,
- population inspect genotype label can be shown or hidden using the authoring tools
- updates to the stacked organism male/female/hetero selection circles to use CSS so they would be more in line with the UI spec (request from Michael when he reviewed my work - he wanted the circles to be thinner in the inspect views).  I did NOT update the raw PNG images since these are also used in the population model.  Updating the …

161597217 population inspect

---

src/components/inspect-panel.sass
src/components/spaces/breeding/breeding-view.sass

This PR fixes two small layout issues on iPad by enforcing stricter CSS layout rules:
- when inspecting gametes in the heredity level, the inspected mouse had an incorrect layout position in the right panel
- text for the total number of offspring was hidden behind reset button

Layout fixes on mobile

---

src/components/spaces/populations/populations-container.tsx
src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

If a user leaves the population model and then comes back to it, the model and graph should remain as they were before.
Note: There is a pre-existing issue where the model will turn black after it is opened too many times. This was made more noticeable in testing this feature, as testing it involved flipping back and forth a lot, but it seems to be the same on master. This branch does not attempt to fix that bug.

Save population state when user switches spaces

---

src/models/spaces/charts/chart-annotation.ts
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

This PR makes changes to the population level graph annotation labels so they they work better with touch screens and have a more uniform approach to being shown and hidden.  Changes include:
- show/hide annotation label on click/touch
- when using mouse, adjust color on hover

172444650 graph label touch

---

src/components/spaces/organisms/organelle-wrapper.tsx

Incorrect calculation of touch position was causing substance addition at the organism level to fail.  Adjust the touch position to have the same container div offset as the mouse position.

Fix touch event positions

---

src/index.html

This PR adds viewport constraints via a meta tag which enable fullscreen to work in both portrait and landscape mode on mobile.  Previously entering fullscreen in some modes (such as portrait) on mobile would cause conflict between our scaling code and the screenfull fullscreen mode (we were getting conflicting screen widths).

add meta tag to define viewport constraints

---

src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/models/spaces/breeding/breeding.ts
src/utilities/genetics.ts

This PR adds the ability to author mutation settings that work on the heredity level.  From the authoring page, users can enable a mutation checkbox, set the initial state of the checkbox, and specify the chance of mutation percentage.  Mutations appear in the nest pair litters when the breed button is pushed an litter offspring are created.
There are open issues regarding the percentages shown in the pie chart, but these are universal to all of the pie chart instances and are better dealt with in a separate PR.

Add mutations to heredity level breeding

---

package-lock.json
package.json
src/components/spaces/organisms/organelle-wrapper.tsx

Makes loading text white and centered.
Getting Fabric.js to correctly load the Ubuntu font proved to be a pain. Instead this simply uses sans-serif.

Style loading text

---

src/components/charts/chart.sass
src/components/charts/chart.tsx
src/components/charts/line-chart-controls.tsx
src/components/charts/line-chart.tsx
src/components/colors.scss
src/components/spaces/populations/populations-charts.tsx
src/models/spaces/populations/mouse-model/mouse-populations-model.ts

Updates the slider to control a pointer, which updates the values in the right-hand pie chart.
Note, this slider works slightly differently in each of four different states:
1. **No pie charts, All points**: Disabled slider
2. **No pie charts, Recent points**: As before: slider from 0-100% shifts chart to see from start to end
3. **Pie charts, All points**: Slider from 0-100% updates right chart from 0-100%
4. **Pie charts, Recent points**: Slider from 0-100% updates right chart from 0-100%, chart shifts so long as right-most point can be the pointer-point, and then remains static while pointer moves within the first 12 months of data.

Pie charts slider

---

cypress/integration/deer-mice-ui.test.ts
cypress/integration/peas-ui.test.ts
src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/components/left-nav-panel.tsx
src/components/spaces/breeding-space.tsx
src/components/spaces/organisms-space.tsx
src/components/spaces/organisms/manipulation-controls.tsx
src/components/spaces/organisms/nucleus-view.tsx
src/components/spaces/organisms/organelle-wrapper.tsx
src/components/spaces/organisms/organisms-container.tsx
src/components/spaces/populations-space.tsx
src/components/spaces/populations/populations-charts.tsx
src/components/spaces/populations/populations-container.tsx
src/components/top-bar.tsx
src/components/zoom-control.tsx
src/index.tsx
src/models/spaces/organisms/mouse/mouse-cell-data.ts
src/models/spaces/organisms/mouse/organisms-mouse.ts
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts
src/models/spaces/populations/populations.ts
src/models/stores.ts
src/models/units.ts
src/utilities/url-params.ts

This introduces the start of some branching based on whether the unit is `"mouse"` or `"pea"`. The largest change is that there is no populations or organism model in the Pea unit (yet), and so this PR adds support for optional models.
It also just barely starts making some UI distinctions between the units (the titles), and adds one small refactoring of mouse-specific files.

Make populations, organism models optional; Start to setup peas unit

---

src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/components/inspect-panel.tsx
src/components/spaces/breeding-space.tsx
src/models/spaces/breeding/breeding.ts

Add authoring option to hide genotypes in parent and/or offspring inspect panels.
Note that the genotypes are still visible elsewhere in the app (gamete toggle, genotype chart) but the author can disable those independently.
Parent genotype hidden in inspect:
http://connected-bio-spaces.concord.org/branch/hide-genotypes/index.html?%7B%22unit%22%3A%22pea%22%2C%22topBar%22%3Atrue%2C%22leftPanel%22%3Afalse%2C%22ui%22%3A%7B%22showBreedingSpace%22%3Atrue%2C%22investigationPanelSpace%22%3A%22breeding%22%7D%2C%22breeding%22%3A%7B%22showParentGenotype%22%3Afalse%2C%22showOffspringGenotype%22%3Atrue%7D%7D
Offspring genotype hidden:
http://connected-bio-spaces.concord.org/branch/hide-genotypes/index.html?%7B%22unit%22%3A%22pea%22%2C%22topBar%22%3Atrue%2C%22leftPanel%22%3Afalse%2C%22ui%22%3A%7B%22sho …

Hide genotypes

---

src/components/inspect-panel.tsx
src/components/spaces/breeding-space.tsx
src/components/spaces/breeding/breeding-container.tsx
src/components/spaces/breeding/breeding-data-nest-panel.tsx
src/components/spaces/breeding/breeding-view.sass
src/components/spaces/breeding/breeding-view.tsx
src/components/spaces/populations-space.tsx
src/components/stacked-organism.pea.sass
src/models/spaces/breeding/breeding.ts

This changes the logic of the gametes toggle switch. Previously, "showing gametes" was one of four different interactions
modes, which also included "breed" (selecting the nest), "select" and "inspect."
This was confusing, because "gametes" acted like "inspect", though it looked like its own independent toggle, and when users clicked to show gametes and then clicked on "inspect" they would leave "gametes" mode.
This disentangles the two, so that gametes being on or off is independent of the interaction mode.

Gametes toggle

---

src/components/inspect-panel.tsx
src/models/units.ts

This changes the standard genotype label so that the male allele is now show on the left.
This also swaps the gametes in the gamete-inspect panel such that the male gamete is on the left (matching the breeding panel).
Testable at
http://connected-bio-spaces.concord.org/branch/reverse-pea-genotype-label/index.html?%7B%22unit%22%3A%22pea%22%2C%22topBar%22%3Atrue%2C%22leftPanel%22%3Afalse%2C%22ui%22%3A%7B%22showBreedingSpace%22%3Atrue%2C%22investigationPanelSpace%22%3A%22breeding%22%7D%7D
(Breed some peas and turn on the gamete switch to show genotypes.)

Reverse pea genotype label

---

src/models/backpack-mouse.ts

Fixes issue in the following model:
[v 2.0.0](https://connected-bio-spaces.concord.org/version/2.0.0/?%7B%22curriculum%22%3A%22mouse%22%2C%22topBar%22%3Afalse%2C%22ui%22%3A%7B%22showPopulationSpace%22%3Atrue%2C%22showBreedingSpace%22%3Afalse%2C%22showOrganismSpace%22%3Atrue%2C%22showDNASpace%22%3Afalse%2C%22investigationPanelSpace%22%3A%22organism%22%7D%2C%22backpack%22%3A%7B%22collectedMice%22%3A%5B%7B%22sex%22%3A%22female%22%2C%22genotype%22%3A%22RR%22%7D%2C%7B%22sex%22%3A%22male%22%2C%22genotype%22%3A%22CC%22%7D%5D%7D%2C%22populations%22%3A%7B%22instructions%22%3A%22%22%2C%22environment%22%3A%22white%22%2C%22showSwitchEnvironmentsButton%22%3Atrue%2C%22includeNeutralEnvironment%22%3Atrue%2C%22initialPopulation%22%3A%7B%22white%22%3A50%2C%22tan%22%3A0%7D%2C%22numHawks%22%3A2%2C%22inherita …

Default to "mouse" if no species in BackpackMouse

---

src/components/spaces/breeding/breeding-view.tsx

This PR improves the positions of the gamete arrows in the peas unit.  I took the path of least resistance on this with the minimal number of changes, but if we ever add another unit, then we will probably want to rework this to be more versatile and use references to the divs that the arrows originate from and end at.

Update gamete arrow positions in pea unit

---

src/components/spaces/breeding/breeding-data-nest-panel.pea.sass
src/components/spaces/breeding/breeding-data-nest-panel.sass
src/components/spaces/breeding/breeding-view.sass
src/components/spaces/breeding/nest-pair.pea.sass
src/components/spaces/breeding/nest-pair.sass
src/components/spaces/breeding/nest-pair.tsx
src/components/stacked-organism.pea.sass
src/components/stacked-organism.tsx
src/models/units.ts

This is a series of small improvements to bring the pea unit display more in line with the UI spec.  Changes include:
- improve the heterozygote selection display
- fix the greenhouse inspect highlight position and z-order
- fix position of breeding label position
- Improve total offspring label position, offspring pen border, and reset button style
- Update pea data panel box size, genotype font and position
- Fix text case on data graph button
- Improve shelf and shelf label positions and sizing

178222326 pea style improvements

---

src/components/spaces/breeding/breeding-container.tsx
src/components/stacked-organism.sass
src/components/stacked-organism.tsx

This PR makes minor improvements to the cursor and organism highlight in relation to the show/hide gamete (based on discussion with Michael):
- collect cursor is shown when collect button is active (regardless of state of show/hide gametes)
- if inspect is active and we are hiding gametes, red inspect cursor is shown
- if inspect is active and we are showing gametes, organism highlight is green circle
- if inspect is active and we are hiding gametes, organism highlight is red circle
- if collect is active and either show or hide gametes is active, organism highlight is blue circle

Improve inspect/collect/gamete cursor states and highlight circles
