concord-consortium/connected-bio-spaces

src/components/left-nav-panel.sass
src/components/left-nav-panel.tsx
src/components/legend.sass
src/components/legend.tsx
src/components/vars.sass

This was one of Kiley's requests to knock out based on Michael's mock-ups.  Changes add a new legend React component that is placed at the bottom of the left nav panel.  This legend is a color key which indicates which colors are used for male, female, heterozygote organisms.

add legend at bottom of left nav panel

---

src/components/charts/bar-chart.tsx
src/components/charts/chart.tsx
src/components/spaces/sample-four-up-space.tsx
src/components/two-up-display.tsx
src/components/zoom-control.sass
src/components/zoom-control.tsx
src/models/spaces/cell-zoom/cell-zoom.ts

Placeholders for cell model data connections

Simple bar chart and zoom buttons

---

package-lock.json
src/components/collect-button.sass
src/components/collect-button.tsx
src/components/left-nav-panel.tsx
src/components/spaces/cell-zoom-space.tsx
src/components/spaces/cell-zoom/OrganelleWrapper.tsx
src/components/spaces/cell-zoom/cell-zoom.sass
src/components/spaces/cell-zoom/cell-zoom.tsx
src/components/spaces/populations/populations.tsx
src/models/backpack-mouse.test.ts
src/models/backpack-mouse.ts
src/models/backpack.test.ts
src/models/backpack.ts
src/models/spaces/cell-zoom/cell-mouse.ts
src/models/spaces/cell-zoom/cell-zoom-row.ts
src/models/spaces/cell-zoom/cell-zoom.ts
src/models/stores.test.ts
src/models/stores.ts

Adds the ability to select mice from the backpack and put them into the cell-zoom view. I have a few questions about how the cell views maintain their state and around component reuse that I'd like to touch base on at some point. I'll leave more specific comments in the code.
@sfentress I'm hoping you can take the lead on this review; @mklewandowski I tagged you to take a look at the `collect-button` changes if you have a chance

Backpack Selection

---

cypress/integration/organism.test.js
cypress/integration/population.test.js
package-lock.json
src/components/left-nav-panel.tsx
src/components/spaces/populations/populations.tsx
src/components/two-up-display.tsx

Beautifully squashed and rebased PR with Eli's help. Updates to cypress tests, and syntax/format fixes.

Adding Cypress tests

---

src/components/charts/bar-chart.tsx
src/components/charts/chart-test.tsx
src/components/charts/chart.tsx
src/components/charts/line-graph.tsx
src/components/collect-button.tsx
src/components/four-up-display.tsx
src/components/left-nav-panel.tsx
src/components/spaces/organisms/organelle-wrapper.tsx
src/components/spaces/organisms/organism-view.tsx
src/components/spaces/organisms/organisms-container.tsx
src/components/zoom-control.tsx

Adding data attributes for automation development.

Adding data attributes for four-up-view, charts, and organisms

---

src/components/spaces/organisms/manipulation-controls.sass
src/components/spaces/organisms/manipulation-controls.tsx
src/components/spaces/organisms/organelle-wrapper.sass
src/components/spaces/organisms/organelle-wrapper.tsx
src/components/spaces/organisms/organisms-container.sass
src/components/spaces/organisms/organisms-container.tsx
src/components/zoom-control.sass
src/models/spaces/organisms/organisms-row.ts

Adds simple assay controls to the cell view, with substance addition controls soon to follow.

Assay tools

---

src/components/four-up-display.sass
src/components/left-nav-panel.tsx
src/components/main-content.sass
src/components/main-content.tsx
src/components/spaces/organisms-space.tsx
src/components/spaces/populations-space.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx

Quick PR to updates title text and colors per PI request.

Fix text and colors on title bars

---

src/components/spaces/organisms-space.tsx
src/components/spaces/organisms/organelle-wrapper.tsx
src/components/spaces/populations-space.tsx
src/components/spaces/proteins/amino-acid-slider.tsx
src/components/spaces/proteins/protein-viewer.tsx
src/components/two-up-display.sass
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts
src/models/spaces/populations/populations.ts
src/models/ui.test.ts
src/models/ui.ts

This is pretty small, except for a shift from storing the right panel state from the ui model to the individual space models.

Amino acid viewer fixes

---

src/components/charts/bar-chart.tsx
src/components/spaces/organisms/manipulation-controls.sass
src/components/spaces/organisms/manipulation-controls.tsx
src/components/spaces/organisms/organelle-wrapper.tsx
src/components/spaces/organisms/organelles/hexagon.yml
src/models/spaces/organisms/organisms-mouse.ts
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts

Substance Additions

---

src/models/spaces/populations/mouse-model/hawks.ts
src/models/spaces/populations/mouse-model/mice.ts

This adds the circling hawks, and hawks now smoothly go down when eating, and back high when circling. This should remove some of the jitteriness that was caused by sudden size changes (though does not remove some jitteriness caused by turning suddenly to follow prey--if folks don't like the way the hawks turn, we can add some smoothing there too.)

Hawks soaring

---

src/components/spaces/populations-space.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx
src/components/vars.sass
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

Add a button to the pop sim graph that allows the user to toggle between all data points and recent data points.

162320674 show all data button graph

---

package-lock.json
package.json

Fixes issues with info popup and new scaling.

Update populations.js to version 0.1.12

---

src/models/spaces/populations/mouse-model/mice.ts

Minor changes to y movement of mice based on Frieda's feedback.

Vertical movement 45

---

src/authoring-schema.json
src/authoring.d.ts
src/components/authoring.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx
src/components/vars.sass
src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/spaces/populations/populations.ts

This adds authoring to enable/disable the graph buttons.
https://connected-bio-spaces.concord.org/branch/author-graph-buttons/?authoring

Author graph buttons

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

Update graph label names in population sim

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

Disable add hawks if authoring defines 0 hawks

---

package-lock.json
package.json
src/components/charts/bar-chart.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx
src/models/spaces/charts/chart-data-set.ts
src/models/spaces/charts/chart-data.ts
src/models/spaces/organisms/organisms-mouse.ts
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts

Add styling to the organism level graph based on the updated UI spec.

Add graph styling to organism view

---

src/components/spaces/organisms-space.tsx
src/components/spaces/proteins/amino-acid-slider.tsx
src/components/spaces/proteins/info-box.sass
src/components/spaces/proteins/protein-viewer.sass
src/components/spaces/proteins/protein-viewer.tsx
src/components/spaces/proteins/protein.sass
src/components/spaces/proteins/protein.tsx
src/models/spaces/organisms/organisms-row.ts
src/models/spaces/organisms/organisms-space.ts

Add a checkbox for showing the info box, make the amino-acid chain visible by default, small CSS tweaks.

Amino Acid Info Box tweaks

---

src/components/spaces/organisms-space.tsx

Update button label case

---

src/models/spaces/breeding/breeding.ts

Randomize the sex of the mouse pairs when we create them in the breeding model.

Randomize nest pair mouse sex

---

package-lock.json
package.json
src/components/charts/bar-chart.tsx
src/components/charts/line-chart.tsx
src/components/colors.scss
src/components/spaces/breeding-space.tsx
src/components/spaces/breeding/breeding-data-nest-panel.sass
src/components/spaces/breeding/breeding-data-nest-panel.tsx
src/components/spaces/breeding/breeding-data.sass
src/components/spaces/breeding/breeding-data.tsx
src/components/spaces/breeding/nest-pair.sass
src/components/spaces/breeding/nest-pair.tsx
src/components/spaces/breeding/pie-chart.tsx
src/components/two-up-display.sass
src/components/two-up-display.tsx
src/components/vars.sass
src/models/spaces/breeding/breeding.ts

Add a breeding data panel which will be used to show the results of breeding nest pairs in the breeding left panel.  New components include:
BreedingData: the container for the right data panel
BreedingDataNestPanel: the component that contains the nest pair button and the pie chart
PieChart: the pie chart which contains stats for each pair

Add breeding data right panel

---

src/components/spaces/breeding/breeding-view.sass
src/components/spaces/breeding/breeding-view.tsx
src/index.html

This does not yet include the custom scroll bar on the right, and related features like the "litter #" label changing when the scrollbar moves.

Styling updates for breeding view

---

src/components/spaces/breeding/breeding-container.sass
src/components/spaces/breeding/breeding-container.tsx
src/components/spaces/breeding/breeding-data-nest-panel.sass
src/components/spaces/breeding/breeding-inspect.sass
src/components/spaces/breeding/breeding-view.sass
src/components/spaces/breeding/breeding-view.tsx
src/components/spaces/breeding/nest-pair.sass

Small updates to bring app more in sync with UI spec:
- update font color, size, weight to match spec
- refactor "nesting" classes in CSS and replace with "breeding" to improve clarity
- add static height to pie chart label to avoid content re-positioning

Ui spec updates

---

src/components/spaces/breeding/pie-chart.tsx

Minor changes to the Pie Chart to adjust label color and font size.

Update pie chart font size and color to match UI spec

---

src/components/spaces/breeding/breeding-view.tsx
src/index.sass

Allow the mouse scroll wheel to scroll litter content

Allow scroll wheel to scroll litter content

---

src/models/spaces/organisms/organisms-space.ts

Change signal protein to activated SP.

Change signal protein to activated SP

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

Update allele names with new nomenclature

Update allele names with new nomenclature

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts

One more set of small fixes to the nomenclature used on the population graph

Fix graph label

---

src/components/spaces/breeding/breeding-data-nest-panel.tsx
src/components/spaces/breeding/pie-chart.tsx

Add tooltips to the breed level pie chart based on the data labels that we pass in.

Add pie chart tooltips

---

src/models/spaces/populations/mouse-model/hawks-mice-interactive.ts

This makes the population stabilization more subtle by
1. Introducing fewer new mice
2. Introducing new mice as babies near other mice of their color, to make it seem like a normal birth

Improve population stabalization

---

src/components/spaces/breeding/breeding-data-nest-panel.tsx
src/components/spaces/breeding/breeding-data.tsx
src/models/spaces/breeding/breeding.ts
src/models/units.ts

This lets the species definitions define how the breeding pie charts are to be created.
Open to suggestions on improving the unit definitions as this gets bigger, since I'll be continuing with the plan that any difference between the units should be defined in those objects (this will need to eventually include the layout differences between mouse and plant breeding). The obvious thing of course will be to split them into different files when they get too big, but if there's something different you can think of let me know.

Peas pie chart

---

cypress/integration/url-params.test.ts
src/authoring-schema.json
src/authoring.d.ts
src/components/app.tsx
src/components/authoring.tsx
src/components/spaces/breeding/breeding-container.sass
src/components/spaces/breeding/breeding-container.tsx
src/components/spaces/populations/populations-container.tsx
src/index.tsx
src/models/stores.ts
src/models/ui.ts

This ended up being much more straight-forward than anticipated, once I backed out of thinking I needed to set the aspect ratio and make a whole bunch of css fixes, and instead left the aspect ratio calculations alone, and simply changed the final width.
With left panel:
http://connected-bio-spaces.concord.org/branch/remove-left-panel-2/index.html?%7B%22unit%22%3A%22pea%22%2C%22topBar%22%3Atrue%2C%22leftPanel%22%3Atrue%2C%22ui%22%3A%7B%22investigationPanelSpace%22%3A%22breeding%22%7D%7D
Without:
http://connected-bio-spaces.concord.org/branch/remove-left-panel-2/index.html?%7B%22unit%22%3A%22pea%22%2C%22topBar%22%3Atrue%2C%22leftPanel%22%3Afalse%2C%22ui%22%3A%7B%22investigationPanelSpace%22%3A%22breeding%22%7D%7D

Authoring to remove left panel

---

cypress/integration/mouse-breeding.test.ts
cypress/integration/peas-ui.test.ts
cypress/integration/url-params.test.ts
package-lock.json
package.json
src/components/inspect-panel-info.animal.tsx
src/components/inspect-panel-info.plant.tsx
src/components/inspect-panel.sass
src/components/inspect-panel.tsx
src/components/spaces/breeding-space.tsx
src/components/spaces/breeding/breeding-view.tsx
src/components/spaces/populations-space.tsx
src/models/units.ts

This was supposed to just be a bunch of tests, but ended up fixing an issue as well in the process.

Add tests for mouse and peas breeding; fix gamete label in peas

---

.travis.yml

Update the python version to the pip awscli install error on Travis which is causing our builds to fail.

update python version to fix pip error

---

src/models/spaces/populations/mouse-model/mouse-populations-model.ts
src/models/units.ts

Update labels to say "Fur Colors" instead of "Fur Color."

Update fur colors label

---

src/components/authoring-common.tsx
src/components/authoring-mice.tsx
src/components/authoring-peas.tsx
src/components/formik-authoring.sass

A collections of small changes to the authoring pages based on QA and feedback.

Custom authoring tweaks

---

src/components/authoring-common.tsx

This PR fixes some small typos in the CBio authoring.

Fix authoring typos
